// <auto-generated />
using BabySiimDiscordBot.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BabySiimDiscordBot.Migrations
{
    [DbContext(typeof(DiscordBotDbContext))]
    [Migration("20200609130226_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.4.20220.10");

            modelBuilder.Entity("BabySiimDiscordBot.Models.FredyConstant", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasMaxLength(256);

                    b.HasKey("Name");

                    b.ToTable("FredyConstants");
                });
#pragma warning restore 612, 618
        }
    }
}
